### ISSUE TITLE
能否加入选项避开中文源语言

### ISSUE THREAD

**Issue by ivysrono** [qinglangee/buggy-translate#1]
就是如果选中的是中文，就不做处理，不弹出翻译浮动框。

**Comment by qinglangee** [comment]
恩，这个可以加一下，目前也不翻译中文

**Comment by ivysrono** [comment]
https://github.com/wallenweel/weel-translation-extension
仅见这个扩展有实现，供参考。

**Comment by qinglangee** [comment]
0.1.6版本只处理英文，审核可能还得几天

**Comment by ivysrono** [comment]
@qinglangee 0.1.6版本还处理纯数字，要不要也屏蔽了。

**Comment by qinglangee** [comment]
恩，可以，多谢提醒
