### ISSUE TITLE
喜欢这个插件,一点小建议 

### ISSUE THREAD

**Issue by ghost** [qinglangee/buggy-translate#4]
希望用更美观精致的图标和弹出框,弹出框最好是半透明的黑底白字圆角矩形小气泡,只显示文字,没有多余内容

**Comment by qinglangee** [comment]
图标是我自己画的，凑合用吧，你知道设计师也不喜欢帮别人免费做logo的
弹出框呢，除非你能出个设计稿，否则程序员哥哥的审美也就这个程度了．．．只有透明度有点发挥的空间．
多余的内容是指什么，英文和音标？
